all:
	cd alu; make all; cd ..
	cd branch_comp; make all; cd ..
	cd data_mem; make all; cd ..
	cd imm_gen; make all; cd ..
	cd instruction_mem; make all; cd ..
	cd program_counter; make all; cd ..
	cd register_file; make all; cd ..
	cd data_mem_ctrl; make all; cd ..
	cd ctrl_logic; make all; cd ..

clean:
	cd alu; make clean; cd ..
	cd branch_comp; make clean; cd ..
	cd data_mem; make clean; cd ..
	cd imm_gen; make clean; cd ..
	cd instruction_mem; make clean; cd ..
	cd program_counter; make clean; cd ..
	cd register_file; make clean; cd ..
	cd data_mem_ctrl; make clean; cd ..
	cd ctrl_logic; make clean; cd ..
